language: c
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
script:
    - ls -l /usr/bin/gcc*
    - export CC=gcc-5 CXX=g++-5
    - cmake -Htest -Bbuild
    - cmake --build build -- VERBOSE=1
    - build/test_msquares
    - build/test_bluenoise
