language: c
script:
    - ls -l /usr/bin/gcc
    - export CC=gcc-5.1
    - export CXX=g++-5.1
    - gcc --version
    - cmake -Htest -Bbuild
    - cmake --build build -- VERBOSE=1
    - build/test_msquares
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.1
    - g++-5.1